org: nashobaems
app: nashoba-ems-scheduler

service: emt-backend

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage,'dev'}
  region: us-east-1

  environment:
    APP_STAGE: ${self:provider.stage}
    AUTH_SECRET: ${file(./serverless-config/secrets.json):AUTH_SECRET}
    ADMIN_SECRET: ${file(./serverless-config/secrets.json):ADMIN_SECRET}
    MONGODB_URI: ${file(./serverless-config/secrets.json):MONGODB_URI}

package:
  individually: true

  exclude:
    - "README.md"
    - ./*.sh
    - tests/**

functions:
  hello:
    handler: src/routes/hello.handler
    events:
      - http:
          path: hello
          method: POST
          cors: true
  
  usersLogin:
    handler: src/routes/users/login.handler
    events:
      - http:
          path: users/login
          method: POST
          cors: true
  
  usersManage:
    handler: src/routes/users/manage.handler
    events:
      - http:
          path: users/manage
          method: POST
          cors: true
  
  crewsManage:
    handler: src/routes/crews/manage.handler
    events:
      - http:
          path: crews/manage
          method: POST
          cors: true
  
  schedulesManage:
    handler: src/routes/schedules/manage.handler
    events:
      - http:
          path: schedules/manage
          method: POST
          cors: true

custom:
  serverless-offline:
    port: 3000
    stage: dev
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  stages:
    - dev

plugins:
  - serverless-webpack
  - serverless-offline # Should be last
